Repository kimkyusoo/On-Purple, pull requests merged in 2022-09, with the labels that each got.

#10 Feature/#9 회원프로필 이미지업로드
  src/main/java/com/project/date/controller/UserController.java
  src/main/java/com/project/date/dto/response/ImgResponseDto.java
  src/main/java/com/project/date/dto/response/UserResponseDto.java
  src/main/java/com/project/date/model/Img.java
  src/main/java/com/project/date/model/User.java
  src/main/java/com/project/date/service/UserService.java
Labels: ✨Feature

#23 Feature/#11 게시글 좋아요
  src/main/java/com/project/date/controller/LikeController.java
  src/main/java/com/project/date/dto/response/PostResponseDto.java
  src/main/java/com/project/date/model/Likes.java
  src/main/java/com/project/date/model/Post.java
  src/main/java/com/project/date/repository/LikeRepository.java
  src/main/java/com/project/date/service/LikeService.java
  src/main/java/com/project/date/service/PostService.java
Labels: ✨Feature, 🎇 필수기능

#30 PostController,UserController 수정 #29
  src/main/java/com/project/date/controller/PostController.java
  src/main/java/com/project/date/controller/UserController.java
Labels: 🖱 자잘한 오류해결

#35 Feature/#17 프로필페이지
  src/main/java/com/project/date/config/SecurityConfiguration.java
  src/main/java/com/project/date/controller/UserController.java
  src/main/java/com/project/date/dto/request/UserInfoUpdateRequestDto.java
  src/main/java/com/project/date/dto/response/ImageResponseDto.java
  src/main/java/com/project/date/dto/response/UserResponseDto.java
  src/main/java/com/project/date/model/Img.java
  src/main/java/com/project/date/model/Post.java
  src/main/java/com/project/date/model/User.java
  src/main/java/com/project/date/model/UserInfo.java
  src/main/java/com/project/date/repository/ImgRepository.java
  src/main/java/com/project/date/repository/UserRepository.java
  src/main/java/com/project/date/service/PostService.java
  src/main/java/com/project/date/service/UserService.java
Labels: ✨Feature
